[package]
name = "yapl"
version = "0.1.0-wip"
edition = "2021"
include = ["src/*", "Cargo.toml", "README.md", "mathjax-wrapper/*", "examples/*", "readme-assets/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
